spring:
  application:
    name: spring-boot-practical
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_practical?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    show-sql: true